ALTER TABLE aluno ADD COLUMN IF NOT EXISTS id_personal BIGINT;
ALTER TABLE aluno ADD COLUMN IF NOT EXISTS plano_id    BIGINT;
ALTER TABLE aluno ADD COLUMN IF NOT EXISTS ativo       BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE aluno ADD COLUMN IF NOT EXISTS telefone    VARCHAR(20);
ALTER TABLE aluno ADD COLUMN IF NOT EXISTS foto_url    VARCHAR(500);
